#workflow rulez comes later here
default:
  tags:
    - glexecutor-docker
  image: public.ecr.aws/docker/library/node:16
  cache: # Cache modules in between jobs, update als the install-npm-dependencies job!
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/
    policy: pull

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  FF_NETWORK_PER_BUILD: "true"
  CI_DEBUG_SERVICES: "true"

stages:
  - prepare
  - validate
  - build
  - test
  - release

install-npm-dependencies:
  stage: prepare
  cache: # Cache modules in between jobs, update als the default job!
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/
    policy: pull-push
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install --silent websocket

lint-job:
  stage: validate
  script:
    # prepare linting for the cli
    - npm run build-commonjs
    - npm run lint
  allow_failure: true

commitlint:
  image: public.ecr.aws/docker/library/node:18
  cache: []
  stage: validate
  before_script:
    - npm install -g @commitlint/{config-conventional,cli}
  script:
    - commitlint --from="$CI_MERGE_REQUEST_DIFF_BASE_SHA" --verbose
  rules:
    - if: $CI_MERGE_REQUEST_IID != null

build-job:
  stage: build
  script:
    - npm run dist
  artifacts:
      paths:
         - build
         - dist
         - commonjs
      expire_in: 30 mins

node-test-job:
  stage: test
  dependencies:
    - build-job
  services:
    - name: public.ecr.aws/docker/library/mongo:4
      alias: mongo
    - public.ecr.aws/docker/library/redis:5.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://local.baqend.com:8081", "http://local.baqend.com:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:2023-34-change-docker-file-16ccb2e4-testing
      alias: local.baqend.com
      command:
        - "--config"
        - "/opt/baqend/lib/conf/config.json"
        - "--with-mongo"
        - "--with-gridfs"
        - "--with-sns"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    - npm run test:node
  artifacts:
    when: always
    reports:
      junit:
        - ./node-result.xml


web-test-job:
  stage: test
  dependencies:
    - build-job
  variables:
    TEST_SERVER: "https://local.baqend.com:8443/v1"
    SE_OPTS: "--log-level FINE"
    ORESTES_CONFIGURATION : $ORESTES_CONFIGURATION_JSON
  services:
    - name: public.ecr.aws/docker/library/mongo:4
      alias: mongo
    - public.ecr.aws/docker/library/redis:5.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://local.baqend.com:8081", "http://local.baqend.com:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:2023-34-change-docker-file-16ccb2e4-testing
      alias: local.baqend.com
      command:
        - "--config"
        - "/opt/baqend/lib/conf/config.json"
        - "--with-mongo"
        - "--with-gridfs"
        - "--with-sns"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    # we need to patch the browserstack runner to allow localhost connections until the issue is resolved
    # https://github.com/modernweb-dev/web/issues/2429
    - sed -i "s/\.replace(.*, localIp)//" node_modules/@web/test-runner-browserstack/dist/browserstackLauncher.js
    - cat node_modules/@web/test-runner-browserstack/dist/browserstackLauncher.js
    - npm run test:browserstack -- --browsers Chrome
  artifacts:
    when: always
    reports:
      junit:
        - ./browserstack-result.xml

release:
  image: public.ecr.aws/docker/library/node:18
  cache: []
  stage: release
  before_script:
    - apt-get update
    - apt-get install -y awscli
    - npm install -g semantic-release @semantic-release/{gitlab,changelog,git,exec}
  script:
    - semantic-release --repository-url $CI_REPOSITORY_URL
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "prerelease"
