#workflow rulez comes later here
image: node:14
stages:      
  - lint    # List of stages for jobs, and their order of execution
  - build

build-job:      
  stage: build
  script:
    - npm ci
    - npm install --silent websocket
    - npm run dist

lint-job:
  stage: lint
  script:
    - npm run lint
   
