#workflow rulez comes later here
default:
  tags:
    - glexecutor-docker
  image: public.ecr.aws/docker/library/node:16
  cache: # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/

variables:
  FF_NETWORK_PER_BUILD: "true"
  CI_DEBUG_SERVICES: "true"

stages:
  - build
  - test

lint-job:
  stage: build
  script:
    - npm link
    - npm link baqend
    - npm run lint
  allow_failure: true

build-job:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm install --silent websocket
    - npm run dist
  artifacts:
      paths:
         - build
         - dist
         - commonjs
      expire_in: 30 mins

node-test-job:
  stage: test
  dependencies:
    - build-job
  services:
    - name: public.ecr.aws/docker/library/mongo:4
      alias: mongo
    - public.ecr.aws/docker/library/redis:5.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://local.baqend.com:8081", "http://local.baqend.com:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:2023-34-change-docker-file-16ccb2e4-testing
      alias: local.baqend.com
      command:
        - "--config"
        - "/opt/baqend/lib/conf/config.json"
        - "--with-mongo"
        - "--with-gridfs"
        - "--with-sns"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    - npm run test:node
  artifacts:
    when: always
    reports:
      junit:
        - ./node-result.xml


web-test-job:
  stage: test
  dependencies:
    - build-job
  variables:
    TEST_SERVER: "https://local.baqend.com:8443/v1"
    SE_OPTS: "--log-level FINE"
    ORESTES_CONFIGURATION : $ORESTES_CONFIGURATION_JSON
  services:
    - name: public.ecr.aws/docker/library/mongo:4
      alias: mongo
    - public.ecr.aws/docker/library/redis:5.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://local.baqend.com:8081", "http://local.baqend.com:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:2023-34-change-docker-file-16ccb2e4-testing
      alias: local.baqend.com
      command:
        - "--config"
        - "/opt/baqend/lib/conf/config.json"
        - "--with-mongo"
        - "--with-gridfs"
        - "--with-sns"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    # we need to patch the browserstack runner to allow localhost connections until the issue is resolved
    # https://github.com/modernweb-dev/web/issues/2429
    - sed -i "s/\.replace(.*, localIp)//" node_modules/@web/test-runner-browserstack/dist/browserstackLauncher.js
    - cat node_modules/@web/test-runner-browserstack/dist/browserstackLauncher.js
    - npm run test:browserstack
  artifacts:
    when: always
    reports:
      junit:
        - ./browserstack-result.xml
