#workflow rulez comes later here
default:
  tags:
    - glexecutor-docker
  image: node:14
  cache: # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/

variables:
  FF_NETWORK_PER_BUILD: "true"
  CI_DEBUG_SERVICES: "true"

stages:
  - lint
  - build
  - test

lint-job:
  stage: lint
  script:
    - echo 'try lint'

build-job:      
  needs:
    - lint-job
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm install --silent websocket
    - npm run dist 
    - npm run test:build  
  artifacts:
      paths:
         - build
         - dist
         - commonjs
      expire_in: 30 mins

node-test-job:
  stage: test
  dependencies: ["build-job"]
  variables:
    TEST_SERVER: "http://orestes:8080/v1"
  services:
    - mongo:4.0.5
    - redis:4.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://orestes:8081", "http://orestes:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:master
      alias: orestes
      command:
        - "--with-mongo"
        - "--with-gridfs"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    - npm run test:node
  artifacts:
    when: always
    reports:
      junit:
        - ./build/test-results/node-result.xml


karma-test-job:
  stage: test
  dependencies: ["build-job"]
  variables:
    TEST_SERVER: "http://orestes:8080/v1"
    KARMA_HOST : "bq3.baqend.com"
  services:
    - mongo:4.0.5
    - redis:4.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://orestes:8081", "http://orestes:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:master
      alias: orestes
      command:
        - "--with-mongo"
        - "--with-gridfs"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  before_script:
   - apt-get update
   - apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget
  script:
    - npm run test:karma --browsers Chrome-Docker --reporters=junit
  artifacts:
    when: always
    reports:
      junit:
        - ./build/test-results/karma-result.xml