#workflow rulez comes later here
image: node:14

stages:      
  - build
  - lint
  - run

build-job:      
  stage: build
  script:
    - npm ci
    - npm install --silent websocket
    - npm run dist 
    - npm run test:build

lint-job:
  stage: lint
  script:
    - echo 'try lint'

run-job:
  stage: run
  needs:
    - build-job
  script:
    - npm ci
    - npm install --silent websocket
    - npm run dist
    - npm run test:node
   
