#workflow rulez comes later here
default:
  tags:
    - glexecutor-docker
  image: node:16
  cache: # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
      - node_modules/

variables:
  FF_NETWORK_PER_BUILD: "true"
  CI_DEBUG_SERVICES: "true"

stages:
  - build
  - test

.lint-job:
  stage: build
  script:
    - npm run lint
  allow_failure: true

.build-job:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm install --silent websocket
    - npm run dist
    - npm run test:build
  artifacts:
    paths:
      - build
      - dist
      - commonjs
    expire_in: 30 mins

create_config:
  stage: build
  script:
    - echo "Creating build directory..."
    - mkdir -p config
    - cp $SSL_CONFIG config/config.json
  artifacts:
    paths:
      - config/config.json
    expire_in: 1 hour

.node-test-job:
  stage: test
  dependencies: ["build-job"]
  variables:
    TEST_SERVER: "http://orestes:8080/v1"
  services:
    - mongo:4.0.5
    - redis:4.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://orestes:8081", "http://orestes:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:master
      alias: orestes
      command:
        - "--with-mongo"
        - "--with-gridfs"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    - npm run test:node
  artifacts:
    when: always
    reports:
      junit:
        - ./build/test-results/node-result.xml

.karma-test-job:
  stage: test
  dependencies:
    - build-job
    - create_config
  variables:
    TEST_SERVER: "https://local.baqend.com:8443/v1"
    KARMA_HOST : "localhost"
    SE_OPTS: "--log-level FINE"
    KEYSTORE_PASSWORD : $LOCAL_KEYSTORE_PASSWORD
  services:
    - mongo:4.0.5
    - redis:4.0
    - name: docker.baqend.com/baqend/node14:master
      alias: node
      command: ["tcp://local.baqend.com:8081", "http://local.baqend.com:8080/v1", "debug"]
    - name: docker.baqend.com/baqend/orestes:2023-34-change-docker-file-35d1b062
      alias: local.baqend.com
      command:
        - "--config"
        - "/builds/config/config.json"
        - "--with-mongo"
        - "--with-gridfs"
        - "--log-level"
        - "trace"
        - "--debug"
        - "--dashboard"
        - "/opt/baqend/node_modules/baqend-dash/dist"
  script:
    - npm run test:karma
  artifacts:
    when: always
    reports:
      junit:
        - ./build/test-results/karma-result.xml

test-job:
  stage: test
  dependencies:
    - create_config
  variables:
    TEST_SERVER: "https://local.baqend.com:8443/v1"
    KARMA_HOST : "localhost"
  services:
    - name: busybox
      alias: local.baqend.com
      command:
        - ls
        - -la
        - /builds/team-backend/orestes/orestes-js/config
  script:
    - ls -la .
    - pwd