#workflow rulez comes later here
image: node:14
stages:      
  - build
  - lint
  - run

build-job:      
  stage: build
  script:
    - npm ci
    - npm install --silent websocket
    - npm run dist

lint-job:
  stage: lint
  script:
    - npm run lint

run-job:
  stage: run
  script:
    - npm run test:node
   
